name: Python Lint

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv with Enable caching
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --group lint

      - name: Ruff Lint
        run: uv run ruff check --output-format=github

      - name: Ruff Format
        run: uv run ruff format

      - name: Pyright
        run: uv run pyright
